//var strVar="";
//strVar += "<div class=\"page-header\">";
//strVar += "<h1>Wizard With Progress Bar using events<\/h1>";
//strVar += "<\/div>";
//strVar += "";
//strVar += "<div id=\"rootwizard\">";
//strVar += "<div class=\"navbar\">";
//strVar += "<div class=\"navbar-inner\">";
//strVar += "<div class=\"container\">";
//strVar += "<ul>";
//strVar += "<li><a href=\"#tab1\" data-toggle=\"tab\">First<\/a><\/li>";
//strVar += "<li><a href=\"#tab2\" data-toggle=\"tab\">Second<\/a><\/li>";
//strVar += "<li><a href=\"#tab3\" data-toggle=\"tab\">Third<\/a><\/li>";
//strVar += "<li><a href=\"#tab4\" data-toggle=\"tab\">Forth<\/a><\/li>";
//strVar += "<li><a href=\"#tab5\" data-toggle=\"tab\">Fifth<\/a><\/li>";
//strVar += "<li><a href=\"#tab6\" data-toggle=\"tab\">Sixth<\/a><\/li>";
//strVar += "<li><a href=\"#tab7\" data-toggle=\"tab\">Seventh<\/a><\/li>";
//strVar += "<\/ul>";
//strVar += "<\/div>";
//strVar += "<\/div>";
//strVar += "<\/div>";
//strVar += "<div id=\"bar\" class=\"progress\">";
//strVar += "<div class=\"progress-bar progress-bar-striped\" role=\"progressbar\" aria-valuenow=\"0\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 0%;\"><span class=\"sr-only\">45% Complete<\/span><\/div>";
//strVar += "<\/div>";
//strVar += "<div class=\"tab-content\">";
//strVar += "<div class=\"tab-pane\" id=\"tab1\">";
//strVar += "1";
//strVar += "<\/div>";
//strVar += "<div class=\"tab-pane\" id=\"tab2\">";
//strVar += "2";
//strVar += "<\/div>";
//strVar += "<div class=\"tab-pane\" id=\"tab3\">";
//strVar += "3";
//strVar += "<\/div>";
//strVar += "<div class=\"tab-pane\" id=\"tab4\">";
//strVar += "4";
//strVar += "<\/div>";
//strVar += "<div class=\"tab-pane\" id=\"tab5\">";
//strVar += "5";
//strVar += "<\/div>";
//strVar += "<div class=\"tab-pane\" id=\"tab6\">";
//strVar += "6";
//strVar += "<\/div>";
//strVar += "<div class=\"tab-pane\" id=\"tab7\">";
//strVar += "7";
//strVar += "<\/div>";
//strVar += "<ul class=\"pager wizard\">";
//strVar += "<li class=\"previous first\" style=\"display:none;\"><a href=\"#\">First<\/a><\/li>";
//strVar += "<li class=\"previous\"><a href=\"#\">Previous<\/a><\/li>";
//strVar += "<li class=\"next last\" style=\"display:none;\"><a href=\"#\">Last<\/a><\/li>";
//strVar += "<li class=\"next\"><a href=\"#\">Next<\/a><\/li>";
//strVar += "<\/ul>";
//strVar += "<\/div>";